"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, Lightbulb, Plus } from "lucide-react";
import { useState } from "react";

const hypothesis = { id: "agent-controls", title: "Independent controls for autonomous agents", statement: "Regulated software teams need an independent runtime control layer for autonomous agents.", status: "Draft", pattern: "AI-agent adoption is creating demand for independent control layers." };

export function Hypotheses({ mode }: { mode?: "new" | "detail" }) {
  if (mode === "new") return <HypothesisForm />;
  if (mode === "detail") return <HypothesisDetail />;
  return <div className="space-y-9"><header className="flex flex-col justify-between gap-5 border-b border-[#30345f] pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow mb-3">Artificial Intelligence / Hypotheses</p><h1 className="font-display text-5xl leading-[.98] sm:text-6xl">Questions worth <em className="text-[#929aff]">testing.</em></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#bfc3dc]">A hypothesis is a testable explanation, not a product recommendation. Validation must look for both supporting and contradictory evidence.</p></div><Link href="/hypotheses/new" className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[#6c72f3] px-3.5 text-xs font-semibold text-white"><Plus size={14} />New hypothesis</Link></header><Link href={`/hypotheses/${hypothesis.id}`} className="surface block p-6 transition hover:border-[#7076f6]"><div className="flex justify-between gap-4"><span className="rounded border border-[#4b559b] bg-[#182048] px-2 py-1 font-mono text-[9px] uppercase tracking-wide text-[#b9c0ff]">{hypothesis.status}</span><Lightbulb size={17} className="text-[#aeb6ff]" /></div><h2 className="mt-5 font-display text-3xl">{hypothesis.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#bfc3dc]">{hypothesis.statement}</p><p className="mt-5 border-t border-[#30345f] pt-4 font-mono text-[10px] text-[#a5abc9]">Linked pattern · Validation not started</p></Link></div>;
}

function HypothesisForm() {
  const [saved, setSaved] = useState(false);
  return <div className="max-w-3xl"><Link href="/hypotheses" className="inline-flex items-center gap-1 text-xs font-semibold text-[#aeb6ff]"><ArrowLeft size={14} />Back to hypotheses</Link><header className="mt-8 border-b border-[#30345f] pb-7"><p className="eyebrow">New hypothesis</p><h1 className="mt-3 font-display text-5xl">Make the claim testable.</h1><p className="mt-4 text-sm leading-7 text-[#bfc3dc]">State the proposed explanation, who it affects, and the assumptions that validation must challenge.</p></header><div className="mt-8 space-y-6"><Field label="Hypothesis title" placeholder="Independent controls for autonomous agents" /><Field label="Statement" placeholder="What must be true for this to be a meaningful explanation?" multiline /><Field label="Target user or market" placeholder="Security and compliance teams at regulated enterprises" /><Field label="Problem observed" placeholder="What evidence-backed problem does this explain?" multiline /><section className="surface p-5"><p className="text-xs font-semibold">Critical assumptions</p><p className="mt-1 text-xs text-[#a5abc9]">Validation will actively search for evidence that weakens these assumptions.</p><div className="mt-4 space-y-2"><Assumption text="Agent adoption is reaching production in regulated teams." /><Assumption text="Existing controls do not meet runtime needs." /></div><button className="mt-4 text-xs font-semibold text-[#aeb6ff]">+ Add assumption</button></section><section className="surface p-5"><p className="eyebrow">Pattern lineage</p><p className="mt-3 text-sm font-semibold">AI-agent adoption is creating demand for independent control layers.</p><p className="mt-1 text-xs text-[#a5abc9]">This preserves the link between your hypothesis and the observations that prompted it.</p></section><button onClick={() => setSaved(true)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[#6c72f3] px-4 text-xs font-semibold text-white">{saved ? <CheckCircle2 size={15} /> : <Lightbulb size={15} />}{saved ? "Draft saved" : "Save hypothesis draft"}</button>{saved && <Link href={`/hypotheses/${hypothesis.id}`} className="ml-4 text-xs font-semibold text-[#aeb6ff]">View draft <ArrowRight className="inline" size={13} /></Link>}</div></div>;
}

function HypothesisDetail() { return <div className="space-y-8"><Link href="/hypotheses" className="inline-flex items-center gap-1 text-xs font-semibold text-[#aeb6ff]"><ArrowLeft size={14} />Back to hypotheses</Link><header className="border-b border-[#30345f] pb-8"><span className="rounded border border-[#4b559b] bg-[#182048] px-2 py-1 font-mono text-[9px] uppercase tracking-wide text-[#b9c0ff]">Draft hypothesis</span><h1 className="mt-5 max-w-4xl font-display text-5xl leading-[.98]">{hypothesis.title}</h1><p className="mt-5 max-w-3xl text-sm leading-7 text-[#bfc3dc]">{hypothesis.statement}</p></header><section className="grid gap-6 lg:grid-cols-2"><section className="surface p-6"><p className="eyebrow">Critical assumptions</p><ul className="mt-4 space-y-3 text-sm text-[#d9ddf3]"><li>01 · Agent adoption is reaching production in regulated teams.</li><li>02 · Existing controls do not meet runtime needs.</li></ul></section><section className="surface p-6"><p className="eyebrow">Testing layer</p><h2 className="mt-4 font-display text-3xl">Deferred.</h2><p className="mt-3 text-sm leading-6 text-[#bfc3dc]">Hypothesis testing needs its own dedicated experience and will be designed separately. This draft remains available for review and refinement.</p></section></section><section className="surface p-6"><p className="eyebrow">Pattern lineage</p><Link href="/patterns/pat-governance" className="mt-3 inline-block text-sm font-semibold text-[#aeb6ff] hover:underline">{hypothesis.pattern}</Link><p className="mt-2 text-xs text-[#a5abc9]">The hypothesis remains separate from the underlying observations and evidence.</p></section><div className="flex gap-2 text-xs text-[#d0b2ed]"><CircleAlert size={14} />Drafts are not conclusions; validation must seek disconfirming evidence.</div></div>; }
function Field({ label, placeholder, multiline }: { label: string; placeholder: string; multiline?: boolean }) { const className = "mt-2 w-full rounded-md border border-[#30345f] bg-[#111735] px-4 py-3 text-sm text-white outline-none placeholder:text-[#72789f] focus:border-[#8993ff]"; return <label className="block text-xs font-semibold">{label}{multiline ? <textarea className={`${className} min-h-24`} placeholder={placeholder} /> : <input className={className} placeholder={placeholder} />}</label>; }
function Assumption({ text }: { text: string }) { return <div className="rounded border border-[#30345f] bg-[#111735] px-3 py-3 text-xs text-[#d9ddf3]">{text}</div>; }
