import Link from "next/link";
import { ArrowLeft, ArrowRight, CircleAlert, Layers3, Lightbulb } from "lucide-react";
import { patterns } from "@/lib/mock-data/dashboard";

export function Patterns({ id }: { id?: string }) {
  const pattern = patterns.find((item) => item.id === id) ?? patterns[0];
  if (id) return <PatternDetail statement={pattern.statement} strength={pattern.strength} window={pattern.window} observations={pattern.observations} counterSignals={pattern.counterSignals} />;
  return <div className="space-y-9"><header className="border-b border-[#30345f] pb-8"><p className="eyebrow mb-3">Artificial Intelligence / Patterns</p><h1 className="font-display text-5xl leading-[.98] sm:text-6xl">What is <em className="text-[#929aff]">recurring.</em></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#bfc3dc]">Patterns connect multiple observations across a defined time window. They are interpretations with explicit counter-signals—not confirmed opportunities.</p></header><div className="grid gap-4 lg:grid-cols-2">{patterns.map((item) => <Link href={`/patterns/${item.id}`} className="surface group p-6 transition hover:-translate-y-0.5 hover:border-[#7076f6]" key={item.id}><div className="flex items-start justify-between"><span className="rounded border border-[#4b559b] bg-[#182048] px-2 py-1 font-mono text-[9px] uppercase tracking-wide text-[#b9c0ff]">Strength {item.strength}</span><Layers3 size={17} className="text-[#aeb6ff]" /></div><h2 className="mt-5 font-display text-3xl leading-tight group-hover:text-[#c2c7ff]">{item.statement}</h2><div className="mt-7 grid grid-cols-3 border-t border-[#30345f] pt-4 font-mono text-[10px] text-[#a5abc9]"><span>{item.window}</span><span>{item.observations} observations</span><span>{item.counterSignals} counter-signals</span></div></Link>)}</div></div>;
}

function PatternDetail({ statement, strength, window, observations, counterSignals }: { statement: string; strength: number; window: string; observations: number; counterSignals: number }) {
  const records = ["Funding activity is clustering around runtime control, observability, and policy layers.", "Product announcements point to governance moving closer to agent deployment workflows.", "Enterprise evaluation needs are appearing alongside increased production adoption."];
  return <div className="space-y-9"><Link href="/patterns" className="inline-flex items-center gap-1 text-xs font-semibold text-[#aeb6ff] hover:text-white"><ArrowLeft size={14} />Back to patterns</Link><header className="border-b border-[#30345f] pb-8"><span className="rounded border border-[#4b559b] bg-[#182048] px-2 py-1 font-mono text-[9px] uppercase tracking-wide text-[#b9c0ff]">Pattern / Strength {strength}</span><h1 className="mt-5 max-w-4xl font-display text-5xl leading-[.98] sm:text-6xl">{statement}</h1><p className="mt-5 max-w-3xl text-sm leading-7 text-[#bfc3dc]">A detected relationship across multiple observations. This is a bounded interpretation, not a confirmed market outcome.</p></header><section className="grid gap-7 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><div><h2 className="text-lg font-semibold">Supporting observations</h2><p className="mt-1 text-xs text-[#a5abc9]">{observations} observations across {window.toLowerCase()}</p><div className="mt-4 space-y-3">{records.map((record, index) => <article className="surface flex gap-4 p-5" key={record}><span className="font-mono text-xs text-[#aeb6ff]">0{index + 1}</span><div><p className="text-sm font-semibold leading-6">{record}</p><p className="mt-2 font-mono text-[10px] text-[#a5abc9]">Linked to 2 evidence items · Signal confidence high</p></div></article>)}</div></div><aside className="space-y-6"><section className="surface p-6"><p className="eyebrow">Counter-signals</p><p className="mt-4 font-mono text-4xl text-[#d0b2ed]">{counterSignals}</p><p className="mt-2 text-sm leading-6 text-[#bfc3dc]">Incumbents may absorb this capability into broader platforms, reducing standalone category potential.</p><div className="mt-5 flex items-start gap-2 border-t border-[#30345f] pt-4 text-xs leading-5 text-[#d0b2ed]"><CircleAlert size={14} className="mt-0.5 shrink-0" />Counter-evidence stays visible in every interpretation.</div></section><section className="surface p-6"><p className="eyebrow">From pattern to hypothesis</p><p className="mt-3 text-sm font-semibold leading-6">Turn this observed relationship into a testable explanation.</p><Link href="/hypotheses/new" className="button mt-5 w-full"><Lightbulb size={14} />Create hypothesis</Link></section></aside></section></div>;
}
