import Link from "next/link";
import { ArrowLeft, ArrowUpRight, CircleAlert, ExternalLink, Link2, ShieldCheck } from "lucide-react";
import { evidenceById } from "@/lib/mock-data/evidence";

export function EvidenceDetail({ id }: { id: string }) {
  const record = evidenceById[id] ?? evidenceById["ev-agent-funding"];
  const contradicts = record.stance === "Counter-evidence";
  return <div className="space-y-9"><Link href="/signals/sig-agent-control" className="inline-flex items-center gap-1 text-xs font-semibold text-[#aeb6ff] hover:text-white"><ArrowLeft size={14} />Back to signal</Link><header className="border-b border-[#30345f] pb-8"><div className="flex flex-wrap items-center gap-2"><span className={`rounded border px-2 py-1 font-mono text-[9px] uppercase tracking-wide ${contradicts ? "border-[#705779] bg-[#241a37] text-[#d0b2ed]" : "border-[#4b559b] bg-[#182048] text-[#b9c0ff]"}`}>{record.stance}</span><span className="eyebrow">Evidence link</span></div><h1 className="mt-5 max-w-4xl font-display text-5xl leading-[.98] sm:text-6xl">{record.claim}</h1><p className="mt-5 max-w-3xl text-sm leading-7 text-[#bfc3dc]">Open the original publication to review the evidence in its full context.</p></header><section className="grid gap-7 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,.8fr)]"><a href={record.url} target="_blank" rel="noreferrer" className="surface group block p-6 transition hover:border-[#7076f6] sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Original source</p><h2 className="mt-3 font-display text-3xl leading-tight group-hover:text-[#c2c7ff]">{record.source}</h2><p className="mt-3 text-sm leading-6 text-[#bfc3dc]">{record.context}</p></div><ExternalLink size={19} className="shrink-0 text-[#aeb6ff]" /></div><div className="mt-8 flex items-center gap-2 border-t border-[#30345f] pt-4 font-mono text-[10px] text-[#aeb6ff]"><Link2 size={13} />Open external evidence</div></a><aside className="space-y-6"><section className="surface p-6"><p className="eyebrow">Record context</p><div className="mt-5 space-y-4"><div><p className="meta">Source type</p><p className="mt-1 text-sm font-semibold">{record.sourceType}</p></div><div><p className="meta">Recorded</p><p className="mt-1 text-sm font-semibold">{record.recordedAt}</p></div></div></section><section className="surface p-6"><div className="flex items-start gap-2"><ShieldCheck size={16} className="mt-0.5 text-[#aeb6ff]" /><div><p className="text-sm font-semibold">Lineage retained</p><p className="mt-1 text-xs leading-6 text-[#bfc3dc]">This external source is linked to the market signal with its stance kept visible.</p></div></div></section>{contradicts && <section className="flex items-start gap-2 rounded-lg border border-[#705779] bg-[#241a37] p-5 text-xs leading-5 text-[#d0b2ed]"><CircleAlert size={15} className="mt-0.5 shrink-0" />Counter-evidence limits the interpretation; it does not invalidate every supporting record.</section>}<Link href="/signals/sig-agent-control" className="inline-flex items-center gap-1 text-xs font-semibold text-[#aeb6ff] hover:underline">Return to signal <ArrowUpRight size={13} /></Link></aside></section></div>;
}
