import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, Clock3, Database, Search, XCircle } from "lucide-react";
import { researchRuns } from "@/lib/mock-data/dashboard";

const stages = ["Plan", "Discover", "Normalize", "Extract", "Verify", "Persist"];

export function ResearchRuns({ detailId }: { detailId?: string }) {
  if (detailId) return <ResearchRunDetail id={detailId} />;
  return <div className="space-y-9"><header className="border-b border-[#30345f] pb-8"><p className="eyebrow mb-3">Research activity</p><h1 className="font-display text-5xl leading-[.98] sm:text-6xl">Research runs.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#bfc3dc]">Collection activity stays visible and source coverage is never presented as complete when it is partial.</p></header><section className="grid gap-4 md:grid-cols-3"><RunMetric icon={CheckCircle2} label="Completed today" value="1" /><RunMetric icon={Clock3} label="In progress" value="1" /><RunMetric icon={CircleAlert} label="Needs review" value="0" /></section><section><h2 className="text-lg font-semibold">Recent runs</h2><p className="mt-1 text-xs text-[#a5abc9]">Each run has a bounded scope, stage history, and source ledger.</p><div className="surface mt-4 overflow-hidden px-5 sm:px-7">{researchRuns.map((run) => <Link className="group flex flex-col gap-4 border-b border-[#30345f] py-5 last:border-0 sm:flex-row sm:items-center" href={`/research/${run.id}`} key={run.id}><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${run.status === "Running" ? "bg-amber-400" : "bg-emerald-400"}`} /><span className="eyebrow">{run.status}</span></div><h3 className="mt-2 text-sm font-semibold group-hover:text-[#aeb6ff]">{run.name}</h3><p className="mt-1 font-mono text-[10px] text-[#a5abc9]">{run.acceptedSources} accepted sources · {run.completedAt}</p></div><div className="w-full sm:w-44"><div className="mb-1.5 flex justify-between font-mono text-[10px] text-[#a5abc9]"><span>Progress</span><span>{run.progress}%</span></div><div className="h-1.5 overflow-hidden rounded bg-[#202750]"><div className="h-full bg-[#7076f6]" style={{ width: `${run.progress}%` }} /></div></div><ArrowRight size={16} className="shrink-0 text-[#aeb6ff]" /></Link>)}</div></section></div>;
}

function ResearchRunDetail({ id }: { id: string }) {
  const run = researchRuns.find((item) => item.id === id) ?? researchRuns[0];
  const running = run.status === "Running";
  return <div className="space-y-9"><Link href="/research" className="inline-flex items-center gap-1 text-xs font-semibold text-[#aeb6ff] hover:text-white">← Back to research runs</Link><header className="border-b border-[#30345f] pb-8"><div className="flex flex-wrap items-center gap-2"><span className={`rounded border px-2 py-1 font-mono text-[9px] uppercase tracking-wide ${running ? "border-amber-300/30 bg-amber-300/10 text-amber-200" : "border-emerald-300/30 bg-emerald-300/10 text-emerald-200"}`}>{run.status}</span><span className="font-mono text-[10px] text-[#a5abc9]">Run ID: {run.id}</span></div><h1 className="mt-5 font-display text-5xl leading-[.98]">{run.name}</h1><p className="mt-4 text-sm text-[#bfc3dc]">Scope: Artificial Intelligence · Global and India · Agent infrastructure, evaluation, and security</p></header><section className="surface p-6 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Pipeline progress</p><p className="mt-2 font-mono text-4xl text-[#aeb6ff]">{run.progress}%</p></div><p className="font-mono text-[10px] text-[#a5abc9]">Request ID: req_72ee2 · Idempotent run</p></div><div className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-6">{stages.map((stage, index) => <div className="rounded border border-[#30345f] bg-[#111735] p-3" key={stage}><span className={`block h-2 w-2 rounded-full ${index < (running ? 4 : 6) ? "bg-[#8993ff]" : "bg-[#3e476e]"}`} /><p className="mt-4 text-xs font-semibold">{stage}</p><p className="mt-1 font-mono text-[9px] text-[#8d93b6]">{index < (running ? 4 : 6) ? "Complete" : running && index === 4 ? "Running" : "Queued"}</p></div>)}</div></section><section className="grid gap-6 md:grid-cols-3"><Info label="Discovered" value="68" detail="Candidate sources" icon={Search} /><Info label="Accepted" value={`${run.acceptedSources}`} detail="After relevance and dedupe" icon={CheckCircle2} /><Info label="Exceptions" value="3" detail="Recoverable extraction failures" icon={XCircle} /></section><section className="surface p-6"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 text-[#c7a8ea]" size={17} /><div><p className="text-sm font-semibold">Partial results are clearly marked.</p><p className="mt-1 text-xs leading-6 text-[#bfc3dc]">This view does not expose raw provider errors. The research engine will retain sanitized failure metadata, retry safely, and finalize coverage before downstream intelligence can treat the run as complete.</p></div></div></section></div>;
}

function RunMetric({ icon: Icon, label, value }: { icon: typeof CheckCircle2; label: string; value: string }) { return <div className="surface p-5"><Icon size={16} className="text-[#aeb6ff]" /><p className="mt-5 font-mono text-3xl text-white">{value}</p><p className="mt-1 text-xs font-semibold">{label}</p></div>; }
function Info({ icon: Icon, label, value, detail }: { icon: typeof Database; label: string; value: string; detail: string }) { return <div className="surface p-5"><Icon size={16} className="text-[#aeb6ff]" /><p className="mt-4 font-mono text-3xl text-white">{value}</p><p className="mt-1 text-xs font-semibold">{label}</p><p className="mt-1 text-xs text-[#a5abc9]">{detail}</p></div>; }
