import Link from "next/link";
import { ArrowRight, BarChart3, CheckCircle2, ShieldCheck } from "lucide-react";

const metrics = [["$284m", "Tracked funding"], ["18", "New signals"], ["3", "Patterns"]];
const bars = [30, 48, 42, 73, 58, 88, 70, 94];

export function HomePage() {
  return <main className="min-h-screen bg-[#090b18] text-[#f4f5ff]">
    <header className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
      <Link href="/" className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-sm border border-[#8993ff] font-display text-2xl text-[#aeb6ff]">i</span><span className="text-[13px] font-bold">intelligence<span className="text-[#8993ff]">.</span></span></Link>
      <div className="flex gap-3"><Link className="inline-flex min-h-10 items-center rounded-md border border-[#30345f] px-3.5 text-xs font-semibold transition hover:bg-[#1a1e3a]" href="/login">Log in</Link><Link className="inline-flex min-h-10 items-center gap-2 rounded-md bg-[#6c72f3] px-3.5 text-xs font-semibold text-white transition hover:bg-[#8187ff]" href="/onboarding">Set up your domain <ArrowRight size={14} /></Link></div>
    </header>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-16 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pt-24">
      <div><p className="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#aeb6ff]">Evidence-backed market intelligence</p><h1 className="mt-5 font-display text-6xl leading-[.9] tracking-[-.03em] sm:text-7xl">See where <em className="text-[#929aff]">AI capital</em> is moving.</h1><p className="mt-7 max-w-xl text-base leading-8 text-[#bfc3dc]">Follow an industry like a market: map investment concentration, track meaningful signals, surface recurring patterns, and test a hypothesis against the evidence.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 rounded-md bg-[#6c72f3] px-5 text-xs font-semibold text-white transition hover:bg-[#8187ff]" href="/onboarding">Choose a domain <ArrowRight size={16} /></Link><Link className="inline-flex min-h-12 items-center rounded-md border border-[#30345f] px-5 text-xs font-semibold transition hover:bg-[#1a1e3a]" href="/workspace">Explore AI intelligence</Link></div><div className="mt-12 flex flex-wrap gap-x-6 gap-y-3 font-mono text-[10px] uppercase tracking-wide text-[#8d93b6]"><span className="inline-flex items-center gap-2"><CheckCircle2 size={13} className="text-[#8993ff]" />Sources stay traceable</span><span className="inline-flex items-center gap-2"><CheckCircle2 size={13} className="text-[#8993ff]" />Counter-evidence is visible</span></div></div>
      <div className="overflow-hidden rounded-xl border border-[#30345f] bg-[#10142d] p-5 sm:p-7"><div className="flex items-center justify-between border-b border-[#30345f] pb-5"><span className="font-mono text-[10px] uppercase tracking-widest text-[#aeb6ff]">AI market pulse</span><span className="rounded border border-[#7180ff]/40 bg-[#1a2050] px-2 py-1 font-mono text-[9px] text-[#b8c0ff]">Updated today</span></div><h2 className="mt-7 font-display text-4xl leading-none">Capital is clustering around agent control and evaluation.</h2><p className="mt-4 text-sm leading-6 text-[#bfc3dc]">A concise brief from the signals, investment activity, and patterns that matter to your selected domain.</p><div className="mt-8 grid grid-cols-3 gap-3">{metrics.map(([value, label]) => <div className="rounded border border-[#30345f] bg-[#151a39] p-3" key={label}><p className="font-mono text-lg">{value}</p><p className="mt-1 text-[10px] text-[#8d93b6]">{label}</p></div>)}</div><div className="mt-7 rounded border border-[#30345f] bg-[#0c1027] p-4"><div className="flex items-center gap-2 text-xs font-semibold"><BarChart3 size={15} className="text-[#929aff]" />Investment concentration</div><div className="mt-4 flex h-20 items-end gap-2">{bars.map((height, index) => <span key={index} className="flex-1 rounded-t bg-[#7076f6]" style={{ height: `${height}%` }} />)}</div><div className="mt-3 flex justify-between font-mono text-[9px] text-[#8d93b6]"><span>Agent infra</span><span>Evaluation</span><span>Security</span></div></div></div>
    </section>
    <footer className="border-t border-[#222750]"><div className="mx-auto flex max-w-7xl items-center gap-2 px-5 py-5 text-xs text-[#8d93b6] sm:px-8"><ShieldCheck size={14} className="text-[#8993ff]" />Intelligence is a trail of evidence, not a claim of certainty.</div></footer>
  </main>;
}
