"use client";

import Link from "next/link";
import { ArrowRight, BarChart3, ChevronDown, CircleAlert, Database, Filter, Search } from "lucide-react";
import { useState } from "react";

export const investmentDomains = [
  { name: "Foundation models", amount: 426, share: 31, change: "+18%", detail: "Model providers, training, and inference", status: "Comparison fixture" },
  { name: "Agent infrastructure", amount: 284, share: 21, change: "+26%", detail: "Runtime control, orchestration, and tooling", status: "Comparison fixture" },
  { name: "AI security & governance", amount: 198, share: 15, change: "+22%", detail: "Identity, guardrails, audit, and policy", status: "Comparison fixture" },
  { name: "AI evaluation & observability", amount: 146, share: 11, change: "+14%", detail: "Testing, monitoring, and reliability", status: "Comparison fixture" },
  { name: "Vertical AI applications", amount: 172, share: 13, change: "+9%", detail: "Industry-specific workflows and software", status: "Comparison fixture" },
  { name: "AI data & tooling", amount: 118, share: 9, change: "+7%", detail: "Data layers, developer tools, and operations", status: "Comparison fixture" },
];

export const investmentRounds = [
  ["Synth Grid", "Agent infrastructure", "Series A", "$54m", "Northzone · Global", "Today"],
  ["Guardrail Systems", "AI security & governance", "Series A", "$36m", "Accel · India", "Yesterday"],
  ["Proofwork", "AI evaluation & observability", "Seed", "$18m", "Lightspeed · Global", "Sep 25"],
  ["Atlas Context", "Foundation models", "Seed", "$12m", "Peak XV · India", "Sep 24"],
  ["Fieldwise", "Vertical AI applications", "Seed", "$8m", "General Catalyst · Global", "Sep 22"],
];

export function InvestmentActivity() {
  const [query, setQuery] = useState("");
  const [period, setPeriod] = useState("Last 30 days");
  const visibleRounds = investmentRounds.filter((round) => round.join(" ").toLowerCase().includes(query.toLowerCase()));

  return <div className="space-y-9"><header className="flex flex-col justify-between gap-6 border-b border-[#30345f] pb-8 md:flex-row md:items-end"><div><p className="eyebrow mb-3">Artificial Intelligence / Investment intelligence</p><h1 className="font-display text-5xl leading-[.98] sm:text-6xl">Where capital is <em className="text-[#929aff]">concentrating.</em></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#bfc3dc]">Compare company funding across the major AI domains, then drill into the rounds and sources behind each total.</p></div><span className="inline-flex w-fit items-center gap-2 rounded border border-[#4b559b] bg-[#182048] px-3 py-2 font-mono text-[10px] text-[#b9c0ff]"><span className="h-1.5 w-1.5 rounded-full bg-[#8993ff]" />Core AI data cutoff: Today, 07:30 UTC</span></header>

    <section className="rounded-lg border border-[#705779] bg-[#16182f] p-5 sm:flex sm:items-start sm:justify-between sm:gap-6"><div className="flex gap-3"><Database size={18} className="mt-0.5 shrink-0 text-[#c7a8ea]" /><div><p className="text-sm font-semibold">Comparison view is ready; only Core AI is live today.</p><p className="mt-1 text-xs leading-6 text-[#bfc3dc]">The six-domain bars are labeled comparison fixtures until each domain is populated in Supabase. They will map to the same funding aggregation when domain data is available.</p></div></div><span className="mt-3 inline-block shrink-0 rounded border border-[#705779] px-2 py-1 font-mono text-[9px] uppercase tracking-wide text-[#d0b2ed] sm:mt-0">Not live data</span></section>

    <section className="surface p-6 sm:p-7"><div className="flex flex-col justify-between gap-4 border-b border-[#30345f] pb-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2"><BarChart3 size={17} className="text-[#aeb6ff]" /><h2 className="text-lg font-semibold">Investment by AI domain</h2></div><p className="mt-2 text-xs text-[#a5abc9]">Comparable disclosed funding across six major AI domains · USD millions</p></div><button className="button w-fit" onClick={() => setPeriod(period === "Last 30 days" ? "Last 90 days" : "Last 30 days")}><Filter size={14} />{period}<ChevronDown size={13} /></button></div><div className="mt-8 grid min-w-[620px] grid-cols-6 items-end gap-4 border-b border-[#30345f] pb-0">{investmentDomains.map((domain) => <div key={domain.name} className="group flex h-72 flex-col justify-end"><div className="mb-3 text-center"><p className="font-mono text-sm font-semibold text-[#c3c9ff]">${domain.amount}m</p><p className="mt-1 font-mono text-[9px] text-emerald-300">{domain.change}</p></div><div className="relative rounded-t-lg bg-gradient-to-t from-[#5961d4] to-[#a5adff] transition group-hover:from-[#717afa] group-hover:to-[#c2c7ff]" style={{ height: `${Math.round((domain.amount / 426) * 100)}%` }}><span className="absolute inset-x-0 bottom-0 h-px bg-white/40" /></div><div className="min-h-16 pt-3 text-center"><p className="text-[11px] font-semibold leading-4 text-[#e5e8ff]">{domain.name}</p><p className="mt-1 text-[9px] text-[#8d93b6]">{domain.share}% of set</p></div></div>)}</div><div className="mt-7 flex flex-wrap items-center gap-x-6 gap-y-2 font-mono text-[10px] text-[#a5abc9]"><span>Total comparison set: <strong className="text-[#d9ddf3]">$1.34b</strong></span><span>Period: {period}</span><span>Six domains</span></div></section>

    <section className="grid gap-8 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]"><div><div className="mb-4"><h2 className="text-lg font-semibold">Company funding tracker</h2><p className="mt-1 text-xs text-[#a5abc9]">Core AI rounds with available source lineage. Select a company to open its profile.</p></div><div className="surface overflow-hidden"><div className="flex items-center gap-2 border-b border-[#30345f] px-5 py-4"><Search size={15} className="text-[#8d93b6]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search company, AI domain, or investor" className="w-full bg-transparent text-xs text-white outline-none placeholder:text-[#72789f]" /></div><div className="overflow-x-auto"><div className="min-w-[700px] px-5"><div className="grid grid-cols-[1.3fr_1.25fr_.7fr_.65fr_1.15fr_.6fr] gap-4 border-b border-[#30345f] py-3 font-mono text-[9px] uppercase tracking-wide text-[#8d93b6]"><span>Company</span><span>AI domain</span><span>Round</span><span>Funding</span><span>Investor / Geography</span><span>Date</span></div>{visibleRounds.map((round) => <Link href={`/companies/${round[0].toLowerCase().replace(/\s+/g, "-")}`} className="grid grid-cols-[1.3fr_1.25fr_.7fr_.65fr_1.15fr_.6fr] gap-4 border-b border-[#30345f] py-4 text-xs transition last:border-0 hover:bg-[#151a39]" key={round[0]}>{round.map((cell, index) => <span className={index === 0 ? "font-semibold text-white" : index === 3 ? "font-mono text-[#aeb6ff]" : "text-[#bfc3dc]"} key={cell}>{cell}</span>)}</Link>)}</div></div></div></div><aside className="space-y-6"><section className="surface p-6"><p className="eyebrow">How to read this</p><h2 className="mt-3 font-display text-3xl leading-tight">Compare capital, then inspect the evidence.</h2><p className="mt-3 text-sm leading-6 text-[#bfc3dc]">Funding indicates attention, not demand or category quality. The company tracker remains the place to inspect individual records.</p><Link href="/signals/sig-agent-control" className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-[#aeb6ff] hover:underline">Review related evidence <ArrowRight size={13} /></Link></section><section className="flex items-start gap-2 rounded-lg border border-[#705779] bg-[#241a37] p-5 text-xs leading-5 text-[#d0b2ed]"><CircleAlert size={15} className="mt-0.5 shrink-0" />Cross-domain values are intentionally marked as fixtures until those domains have their own accepted funding records.</section></aside></section>
  </div>;
}
