"use client";

import { Activity, AlertTriangle, CheckCircle2, ClipboardList, Clock3, Database, RefreshCw, Search, ShieldCheck, Waypoints } from "lucide-react";
import { useMemo, useState } from "react";

const runs = [
  { started: "Sep 29, 07:30 UTC", workflow: "Research Engine", id: "req_93af71", domain: "Core AI", status: "Completed", duration: "4m 12s", attempts: 1, output: "42 / 18 / 6", calls: 14, cost: "$0.86", error: "—" },
  { started: "Sep 29, 06:00 UTC", workflow: "RE09", id: "req_f7b2c1", domain: "Core AI", status: "Partial", duration: "6m 43s", attempts: 2, output: "35 / 14 / 4", calls: 11, cost: "$0.61", error: "2 source extractions timed out" },
  { started: "Sep 28, 18:00 UTC", workflow: "RE07", id: "req_26c9ab", domain: "Foundation models", status: "Completed", duration: "3m 47s", attempts: 1, output: "28 / 12 / 3", calls: 9, cost: "$0.44", error: "—" },
  { started: "Sep 28, 12:00 UTC", workflow: "RE08", id: "req_3f80d4", domain: "AI governance", status: "Failed", duration: "1m 08s", attempts: 3, output: "0 / 0 / 0", calls: 3, cost: "$0.09", error: "Provider rate limit" },
];
const usage = [
  { date: "Sep 29", workflow: "Research Engine", provider: "OpenAI", model: "gpt-5", requests: 14, input: "184k", output: "22k", cost: "$0.86", latency: "2.4s", failed: 0 },
  { date: "Sep 29", workflow: "RE09", provider: "OpenAI", model: "gpt-5-mini", requests: 11, input: "96k", output: "13k", cost: "$0.61", latency: "1.8s", failed: 1 },
  { date: "Sep 28", workflow: "RE07", provider: "OpenAI", model: "gpt-5", requests: 9, input: "126k", output: "17k", cost: "$0.44", latency: "2.1s", failed: 0 },
];
const requests = [
  { time: "Sep 29, 07:33", id: "req_93af71", workflow: "Research Engine / classify", model: "OpenAI / gpt-5", success: true, latency: "2.4s", tokens: "18,430 / 2,190", cost: "$0.09", error: "—", related: "run_719c" },
  { time: "Sep 29, 06:04", id: "req_f7b2c1", workflow: "RE09 / extract", model: "OpenAI / gpt-5-mini", success: false, latency: "8.0s", tokens: "0 / 0", cost: "$0.00", error: "rate_limit", related: "run_644b" },
  { time: "Sep 28, 12:01", id: "req_3f80d4", workflow: "RE08 / verify", model: "OpenAI / gpt-5-mini", success: false, latency: "5.1s", tokens: "3,220 / 0", cost: "$0.03", error: "provider_timeout", related: "run_2e3a" },
];
const audit = [
  ["Sep 29, 07:37", "user · usr_aman", "signal.accepted", "signal · sig_341", "req_93af71", "Human review gate accepted"],
  ["Sep 29, 06:09", "service · re09", "run.partial", "research_run · run_644b", "req_f7b2c1", "Source extraction timeout recorded"],
  ["Sep 28, 12:02", "system", "request.failed", "job_run · job_997", "req_3f80d4", "Provider timeout"],
];
const countRows = [["Research runs", "Completed", "38"], ["Sources", "Collected", "612"], ["Evidence", "Accepted", "284"], ["Signals", "Draft / accepted / rejected", "14 / 36 / 3"], ["Observations", "Draft / accepted", "5 / 18"], ["Patterns", "Emerging / persistent / weakening", "4 / 8 / 1"], ["Hypotheses", "Ready / validating / complete", "3 / 2 / 7"], ["Insights", "Draft / published", "4 / 11"]];
const tabs = ["Overview", "Workflow runs", "AI usage", "Requests & errors", "Audit log", "System counts"] as const;
type Tab = typeof tabs[number];

export function AdminPanel() {
  const [tab, setTab] = useState<Tab>("Overview");
  const [range, setRange] = useState("7 days");
  const [query, setQuery] = useState("");
  const [refreshed, setRefreshed] = useState("Just now");
  const filteredRuns = useMemo(() => runs.filter((run) => Object.values(run).join(" ").toLowerCase().includes(query.toLowerCase())), [query]);
  const filteredRequests = useMemo(() => requests.filter((request) => Object.values(request).join(" ").toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="space-y-7"><header className="flex flex-col justify-between gap-5 border-b border-[#30345f] pb-7 xl:flex-row xl:items-end"><div><p className="eyebrow mb-3">Internal / workspace operations</p><h1 className="font-display text-5xl leading-[.98] sm:text-6xl">Admin <em className="text-[#929aff]">control.</em></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#bfc3dc]">Read-only pipeline health, model usage, costs, request lineage, and review activity for this workspace.</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded border border-[#4b559b] bg-[#182048] px-3 py-2 font-mono text-[10px] text-[#b9c0ff]"><ShieldCheck className="mr-1 inline" size={13} />Owner / admin only</span><button className="button" onClick={() => setRefreshed("Just now")}><RefreshCw size={14} />Refresh</button></div></header><div className="flex flex-col gap-3 border-b border-[#30345f] pb-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-1 overflow-x-auto">{tabs.map((item) => <button onClick={() => { setTab(item); setQuery(""); }} className={`whitespace-nowrap rounded px-3 py-2 text-xs font-semibold ${tab === item ? "bg-[#20265c] text-white" : "text-[#a5abc9] hover:bg-[#171c42]"}`} key={item}>{item}</button>)}</div><div className="flex items-center gap-2"><select value={range} onChange={(event) => setRange(event.target.value)} className="rounded border border-[#30345f] bg-[#111735] px-3 py-2 text-xs text-white outline-none"><option>Today</option><option>7 days</option><option>30 days</option></select><span className="font-mono text-[10px] text-[#8d93b6]">Updated {refreshed} · UTC</span></div></div>{tab === "Overview" && <Overview range={range} />}{tab === "Workflow runs" && <WorkflowRuns query={query} setQuery={setQuery} rows={filteredRuns} />}{tab === "AI usage" && <Usage range={range} />}{tab === "Requests & errors" && <Requests query={query} setQuery={setQuery} rows={filteredRequests} />}{tab === "Audit log" && <Audit />}{tab === "System counts" && <Counts />}</div>;
}

function Overview({ range }: { range: string }) { const bars = [40, 58, 44, 74, 68, 87, 63]; return <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Waypoints} label="Workflow runs" value="42" detail="35 completed · 2 partial · 1 failed" /><Stat icon={Activity} label="LLM requests" value="128" detail="126 successful · 2 failed" /><Stat icon={Database} label="Total tokens" value="1.24m" detail="1.04m input · 0.20m output" /><Stat icon={Clock3} label="Estimated cost" value="$7.82" detail="Estimated · not provider-reconciled" /><Stat icon={CheckCircle2} label="Evidence accepted" value="284" detail="From 612 collected sources" /><Stat icon={ClipboardList} label="Draft signals" value="14" detail="Awaiting human review gate" /><Stat icon={AlertTriangle} label="Last failure" value="06:04 UTC" detail="RE09 · provider rate limit" /><Stat icon={RefreshCw} label="Last success" value="07:37 UTC" detail="Research Engine completed" /></section><section className="grid gap-5 xl:grid-cols-2"><Chart title="Daily requests & estimated cost" subtitle={`${range} · Estimated cost`} bars={bars} labels={["23", "24", "25", "26", "27", "28", "29"]} /><Chart title="Daily workflow outcome" subtitle="Completed versus partial / failed" bars={[38, 62, 50, 78, 70, 88, 64]} labels={["23", "24", "25", "26", "27", "28", "29"]} secondary /></section><section className="surface p-6"><p className="eyebrow">Data handling</p><p className="mt-3 text-sm leading-6 text-[#bfc3dc]">This preview uses safe fixture data. The live view reads only RLS-scoped admin views; it never returns credentials, raw prompts, full model responses, or unrestricted metadata.</p></section></>; }
function WorkflowRuns({ query, setQuery, rows }: { query: string; setQuery: (value: string) => void; rows: typeof runs }) { return <section className="surface overflow-hidden"><Toolbar query={query} setQuery={setQuery} placeholder="Search run ID, workflow, domain, or status" /><Table headers={["Started", "Workflow / ID", "Domain", "Status", "Duration", "Attempts", "Sources / evidence / output", "LLM calls", "Estimated cost", "Safe error"]}>{rows.map((run) => <tr key={run.id}><Cell>{run.started}</Cell><Cell><b>{run.workflow}</b><Small>{run.id}</Small></Cell><Cell>{run.domain}</Cell><Cell><Status value={run.status} /></Cell><Cell>{run.duration}</Cell><Cell>{run.attempts}</Cell><Cell>{run.output}</Cell><Cell>{run.calls}</Cell><Cell>{run.cost}</Cell><Cell>{run.error}</Cell></tr>)}</Table><Empty visible={!rows.length} /></section>; }
function Usage({ range }: { range: string }) { return <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Activity} label="Requests / calls" value="128" detail={`${range} selected`} /><Stat icon={CheckCircle2} label="Failure rate" value="1.6%" detail="2 failed requests" /><Stat icon={Clock3} label="Average latency" value="2.2s" detail="Successful calls only" /><Stat icon={Database} label="Estimated cost" value="$7.82" detail="Estimated · not provider-reconciled" /></section><section className="surface overflow-hidden"><Table headers={["Day", "Workflow", "Provider / model", "Calls", "Input", "Output", "Estimated cost", "Avg latency", "Failed"]}>{usage.map((row) => <tr key={`${row.date}-${row.workflow}`}><Cell>{row.date}</Cell><Cell>{row.workflow}</Cell><Cell>{row.provider} / {row.model}</Cell><Cell>{row.requests}</Cell><Cell>{row.input}</Cell><Cell>{row.output}</Cell><Cell>{row.cost}</Cell><Cell>{row.latency}</Cell><Cell>{row.failed}</Cell></tr>)}</Table></section></>; }
function Requests({ query, setQuery, rows }: { query: string; setQuery: (value: string) => void; rows: typeof requests }) { return <section className="surface overflow-hidden"><Toolbar query={query} setQuery={setQuery} placeholder="Search exact request ID, workflow, provider, model, or error code" /><Table headers={["Timestamp", "Request ID", "Workflow / operation", "Provider / model", "Result", "Latency", "Tokens in / out", "Estimated cost", "Error code", "Related run"]}>{rows.map((row) => <tr key={row.id}><Cell>{row.time}</Cell><Cell><code>{row.id}</code></Cell><Cell>{row.workflow}</Cell><Cell>{row.model}</Cell><Cell><Status value={row.success ? "Success" : "Failed"} /></Cell><Cell>{row.latency}</Cell><Cell>{row.tokens}</Cell><Cell>{row.cost}</Cell><Cell>{row.error}</Cell><Cell><code>{row.related}</code></Cell></tr>)}</Table><Empty visible={!rows.length} /></section>; }
function Audit() { return <section className="surface overflow-hidden"><Table headers={["Timestamp", "Actor", "Action", "Target", "Request ID", "Safe metadata"]}>{audit.map((row) => <tr key={row[0]}>{row.map((cell, index) => <Cell key={cell}>{index === 2 ? <span className="font-semibold text-[#c3c9ff]">{cell}</span> : cell}</Cell>)}</tr>)}</Table><div className="border-t border-[#30345f] px-5 py-4 text-xs leading-5 text-[#a5abc9]">Signal acceptance and rejection are retained here as the system’s required human-review gate. Sensitive metadata keys are redacted before display.</div></section>; }
function Counts() { return <section className="surface overflow-hidden"><Table headers={["Object", "Status breakdown", "Current total"]}>{countRows.map((row) => <tr key={row[0]}><Cell><b>{row[0]}</b></Cell><Cell>{row[1]}</Cell><Cell>{row[2]}</Cell></tr>)}</Table><div className="border-t border-[#30345f] px-5 py-4 text-xs text-[#a5abc9]">Diagnostic totals only. No direct editing or deletion is available in the admin panel.</div></section>; }
function Stat({ icon: Icon, label, value, detail }: { icon: typeof Activity; label: string; value: string; detail: string }) { return <section className="surface p-5"><div className="flex items-center justify-between"><p className="meta">{label}</p><Icon size={15} className="text-[#aeb6ff]" /></div><p className="mt-4 font-mono text-2xl font-semibold text-[#e5e8ff]">{value}</p><p className="mt-2 text-[10px] leading-4 text-[#a5abc9]">{detail}</p></section>; }
function Chart({ title, subtitle, bars, labels, secondary = false }: { title: string; subtitle: string; bars: number[]; labels: string[]; secondary?: boolean }) { return <section className="surface p-6"><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-[#a5abc9]">{subtitle}</p></div><div className="mt-8 flex h-40 items-end gap-3 border-b border-[#30345f] pb-0">{bars.map((bar, index) => <div className="flex flex-1 flex-col items-center gap-2" key={labels[index]}><div className={`w-full rounded-t ${secondary ? "bg-[#8766c5]" : "bg-[#6872eb]"}`} style={{ height: `${bar}%` }} /><span className="font-mono text-[9px] text-[#8d93b6]">{labels[index]}</span></div>)}</div></section>; }
function Toolbar({ query, setQuery, placeholder }: { query: string; setQuery: (value: string) => void; placeholder: string }) { return <div className="flex flex-col gap-3 border-b border-[#30345f] p-4 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded border border-[#30345f] bg-[#111735] px-3 py-2"><Search size={14} className="text-[#8d93b6]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-xs text-white outline-none placeholder:text-[#72789f]" placeholder={placeholder} /></label><select className="rounded border border-[#30345f] bg-[#111735] px-3 py-2 text-xs text-white"><option>All statuses</option><option>Completed</option><option>Partial</option><option>Failed</option></select></div>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-left text-xs"><thead className="border-b border-[#30345f] bg-[#111735] font-mono text-[9px] uppercase tracking-wide text-[#8d93b6]"><tr>{headers.map((header) => <th className="px-4 py-3 font-medium" key={header}>{header}</th>)}</tr></thead><tbody className="divide-y divide-[#30345f] text-[#bfc3dc]">{children}</tbody></table></div>; }
function Cell({ children }: { children: React.ReactNode }) { return <td className="max-w-[240px] px-4 py-3 align-top leading-5">{children}</td>; }
function Small({ children }: { children: React.ReactNode }) { return <span className="mt-1 block font-mono text-[10px] text-[#8d93b6]">{children}</span>; }
function Status({ value }: { value: string }) { const tone = /failed/i.test(value) ? "border-rose-400/30 bg-rose-400/10 text-rose-200" : /partial/i.test(value) ? "border-amber-300/30 bg-amber-300/10 text-amber-200" : /running|queued/i.test(value) ? "border-[#7782f7]/30 bg-[#20265c] text-[#c3c9ff]" : "border-emerald-300/30 bg-emerald-300/10 text-emerald-200"; return <span className={`rounded border px-2 py-1 font-mono text-[9px] uppercase tracking-wide ${tone}`}>{value}</span>; }
function Empty({ visible }: { visible: boolean }) { return visible ? <p className="px-5 py-12 text-center text-sm text-[#a5abc9]">No records match the current filters.</p> : null; }
