"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, ChevronLeft, ShieldCheck } from "lucide-react";
import { useState } from "react";

export function PhoneOtpForm() {
  const [step, setStep] = useState<"phone" | "code">("phone");
  const [phone, setPhone] = useState("");
  const [code, setCode] = useState("");
  const ready = phone.replace(/\D/g, "").length >= 10;

  return <main className="grid min-h-screen bg-[#090b18] lg:grid-cols-[1fr_.85fr]">
    <section className="hidden border-r border-[#282d5b] bg-[#0d1025] p-10 text-white lg:flex lg:flex-col"><Link href="/" className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-sm border border-[#8993ff] font-display text-2xl text-[#aeb6ff]">i</span><span className="text-[13px] font-bold">intelligence<span className="text-[#8993ff]">.</span></span></Link><div className="my-auto max-w-md"><p className="font-mono text-[10px] font-semibold uppercase tracking-[.14em] text-[#aeb6ff]">A personal intelligence workspace</p><h1 className="mt-5 font-display text-5xl leading-[.98]">Know the market.<br /><em className="text-[#929aff]">Keep the evidence.</em></h1><p className="mt-6 max-w-sm text-sm leading-7 text-[#bfc3dc]">Track meaningful shifts in a domain, where capital is concentrating, and which hypotheses survive scrutiny.</p></div><div className="border-t border-[#30345f] pt-5 text-xs text-[#8d93b6]"><ShieldCheck className="mr-2 inline text-[#8993ff]" size={14} />Workspace-scoped and evidence-backed</div></section>
    <section className="flex items-center justify-center bg-[#090b18] px-5 py-12"><div className="w-full max-w-md"><Link href="/" className="mb-12 inline-flex items-center gap-1 text-xs font-semibold text-[#8d93b6] hover:text-white"><ChevronLeft size={15} />Back to home</Link>{step === "phone" ? <><p className="eyebrow">Welcome</p><h2 className="mt-3 font-display text-5xl leading-none">Continue to your workspace.</h2><p className="mt-4 text-sm leading-6 text-[#bfc3dc]">Enter your phone number and we’ll send a one-time verification code.</p><label className="mt-8 block text-xs font-semibold">Phone number<input className="mt-2 w-full rounded-md border border-[#30345f] bg-[#111735] px-4 py-3 text-sm text-white outline-none placeholder:text-[#72789f] focus:border-[#8993ff] focus:ring-2 focus:ring-[#6c72f3]/20" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="+91 98765 43210" inputMode="tel" autoComplete="tel" /></label><button className="mt-5 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-md bg-[#6c72f3] px-3.5 text-xs font-semibold text-white transition hover:bg-[#8187ff] disabled:cursor-not-allowed disabled:opacity-50" disabled={!ready} onClick={() => setStep("code")}>Send verification code <ArrowRight size={15} /></button><p className="mt-6 text-xs leading-5 text-[#8d93b6]">By continuing, you agree to receive a one-time code. Authentication will be connected to Supabase before release.</p></> : <><p className="eyebrow">Verify your number</p><h2 className="mt-3 font-display text-5xl leading-none">Enter your code.</h2><p className="mt-4 text-sm leading-6 text-[#bfc3dc]">We sent a six-digit code to {phone}.</p><input className="mt-8 w-full rounded-md border border-[#30345f] bg-[#111735] px-4 py-4 text-center font-mono text-xl tracking-[.45em] text-white outline-none focus:border-[#8993ff]" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} inputMode="numeric" autoFocus /><Link className={`mt-5 inline-flex min-h-10 w-full items-center justify-center gap-2 rounded-md bg-[#6c72f3] px-3.5 text-xs font-semibold text-white transition hover:bg-[#8187ff] ${code.length !== 6 ? "pointer-events-none opacity-50" : ""}`} href="/onboarding"><CheckCircle2 size={15} />Verify and continue</Link><button className="mt-5 w-full text-xs font-semibold text-[#929aff] hover:underline" onClick={() => setStep("phone")}>Use a different number</button></>}</div></section>
  </main>;
}
