"use client";

import { Bell, Check, ChevronRight, Globe2, SlidersHorizontal, Sparkles } from "lucide-react";
import { useState } from "react";

const topics = ["Agent infrastructure", "AI evaluation", "AI security", "Enterprise adoption", "Foundation models"];
const regions = ["India", "United States", "Europe"];

function Preference({ label, detail, enabled, onChange }: { label: string; detail: string; enabled: boolean; onChange: () => void }) {
  return <button type="button" onClick={onChange} className="flex w-full items-center justify-between gap-6 border-b border-[#30345f] py-5 text-left last:border-b-0"><span><span className="block text-sm font-semibold text-white">{label}</span><span className="mt-1 block text-xs leading-5 text-[#bfc3dc]">{detail}</span></span><span aria-hidden className={`relative h-6 w-11 shrink-0 rounded-full transition ${enabled ? "bg-[#747bf4]" : "bg-[#262c4c]"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${enabled ? "left-6" : "left-1"}`} /></span></button>;
}

export function WorkspaceSettings() {
  const [selectedTopics, setSelectedTopics] = useState(topics.slice(0, 3));
  const [selectedRegions, setSelectedRegions] = useState(regions.slice(0, 2));
  const [preferences, setPreferences] = useState({ daily: true, weekly: false });
  const toggle = (item: string, current: string[], update: (items: string[]) => void) => update(current.includes(item) ? current.filter((value) => value !== item) : [...current, item]);

  return <div className="space-y-9"><header className="border-b border-[#30345f] pb-8"><p className="eyebrow mb-3">Personal workspace</p><h1 className="font-display text-5xl leading-[.98] sm:text-6xl">Settings &amp; <em className="text-[#929aff]">focus.</em></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#bfc3dc]">Set the market context that shapes what you see. These choices stay inside your personal workspace.</p></header>

    <section className="surface overflow-hidden"><div className="flex items-start justify-between gap-4 border-b border-[#30345f] p-6 sm:p-7"><div><p className="eyebrow">Active domain</p><h2 className="mt-2 text-xl font-semibold">Artificial Intelligence</h2><p className="mt-2 text-xs leading-5 text-[#bfc3dc]">Your current lens for signals, investment activity, and emerging patterns.</p></div><span className="grid h-10 w-10 place-items-center rounded-lg border border-[#535ca5] bg-[#171c42] text-[#aeb6ff]"><Sparkles size={18} /></span></div><div className="grid divide-y divide-[#30345f] sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div className="p-5"><p className="meta">Workspace</p><p className="mt-2 text-sm font-semibold">Aman&apos;s workspace</p></div><div className="p-5"><p className="meta">Domain status</p><p className="mt-2 inline-flex items-center gap-1.5 text-sm font-semibold text-[#b8c0ff]"><Check size={14} />Configured</p></div><button type="button" className="flex items-center justify-between gap-3 p-5 text-left text-sm font-semibold transition hover:bg-[#12183a]">Change domain <ChevronRight size={16} className="text-[#aeb6ff]" /></button></div></section>

    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="surface p-6 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#171c42] text-[#aeb6ff]"><SlidersHorizontal size={17} /></span><div><h2 className="text-base font-semibold">Research focus</h2><p className="mt-1 text-xs text-[#bfc3dc]">Tune the themes that should receive more attention.</p></div></div><div className="mt-7"><p className="meta">Topics</p><div className="mt-3 flex flex-wrap gap-2">{topics.map((topic) => { const selected = selectedTopics.includes(topic); return <button type="button" key={topic} onClick={() => toggle(topic, selectedTopics, setSelectedTopics)} className={`rounded-full border px-3 py-2 text-xs font-semibold transition ${selected ? "border-[#7782f7] bg-[#20265c] text-white" : "border-[#30345f] bg-[#101633] text-[#a5abc9] hover:border-[#626bc2] hover:text-white"}`}>{selected && <Check className="mr-1 inline" size={12} />}{topic}</button>; })}</div></div><div className="mt-7 border-t border-[#30345f] pt-6"><p className="meta">Regions</p><div className="mt-3 flex flex-wrap gap-2">{regions.map((region) => { const selected = selectedRegions.includes(region); return <button type="button" key={region} onClick={() => toggle(region, selectedRegions, setSelectedRegions)} className={`rounded-full border px-3 py-2 text-xs font-semibold transition ${selected ? "border-[#7782f7] bg-[#20265c] text-white" : "border-[#30345f] bg-[#101633] text-[#a5abc9] hover:border-[#626bc2] hover:text-white"}`}>{selected && <Check className="mr-1 inline" size={12} />}{region}</button>; })}</div></div></section>

      <section className="surface p-6 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#171c42] text-[#aeb6ff]"><Globe2 size={17} /></span><div><h2 className="text-base font-semibold">Coverage</h2><p className="mt-1 text-xs text-[#bfc3dc]">The cadence your workspace uses to surface relevant market change.</p></div></div><div className="mt-7 rounded-lg border border-[#30345f] bg-[#101633] p-4"><p className="meta">Research cadence</p><p className="mt-2 text-sm font-semibold">Daily market brief</p><p className="mt-1 text-xs text-[#bfc3dc]">A calm summary of meaningful changes, not every headline.</p></div></section></div>

    <section className="surface p-6 sm:p-7"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#171c42] text-[#aeb6ff]"><Bell size={17} /></span><div><h2 className="text-base font-semibold">Notifications</h2><p className="mt-1 text-xs text-[#bfc3dc]">Decide when you want your intelligence workspace to nudge you.</p></div></div><div className="mt-5"><Preference label="Daily intelligence brief" detail="Receive a concise daily view of the most meaningful changes." enabled={preferences.daily} onChange={() => setPreferences((value) => ({ ...value, daily: !value.daily }))} /><Preference label="Weekly reflection" detail="A weekly summary of saved intelligence and developing ideas." enabled={preferences.weekly} onChange={() => setPreferences((value) => ({ ...value, weekly: !value.weekly }))} /></div></section>
  </div>;
}
